name: JupyterMS
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pyteomics
  - vaex
  - ipywidgets
  - jupyter
  - pytables
  - pyarrow>=0.15
  - seq-to-first-iso
  - pip :
    - pyopenms

